spring:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: false
  datasource:
    initialization-mode: always
    platform: postgres
    url: postgresql://localhost:5432/project
    username: postgres
    password: admin
  thymeleaf:
    template-resolver-order: 1
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 23500386943-9hrfde5uu9qvugpa1bq3cacdsqbbdu0o.apps.googleusercontent.com
            clientSecret: 9cVEFgH3MjLjwbEZ08gDq_hQ
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

innova:
  app:
    jwtSecret: jwtInnovaSecretKey
    jwtSecretVerification: Iamhereforverification
    jwtExpiration: 86400000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:4200/oauth2/redirect
